# Generated by Django 2.2.8 on 2019-12-12 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.CharField(max_length=100)),
                ('konten', models.CharField(max_length=3000)),
                ('gambar', models.CharField(max_length=200)),
            ],
        ),
    ]
