# Generated by Django 2.2.8 on 2019-12-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_fitur', '0003_auto_20191212_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kategori',
            field=models.CharField(default='Dessert', max_length=200),
        ),
    ]
